# Generated by Django 3.0.8 on 2020-08-15 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='emergency',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='insurance',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='pension',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='spending',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Percentages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=5, default=0.005, max_digits=10)),
                ('emergency', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, default=0.2, max_digits=10)),
                ('pension', models.DecimalField(decimal_places=2, default=0.2, max_digits=10)),
                ('spending', models.DecimalField(decimal_places=2, default=0.495, max_digits=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_percentages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
