# Generated by Django 3.0.8 on 2020-08-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20200815_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentages',
            name='emergency',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='percentages',
            name='insurance',
            field=models.DecimalField(decimal_places=4, default=0.2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='percentages',
            name='pension',
            field=models.DecimalField(decimal_places=4, default=0.2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='percentages',
            name='spending',
            field=models.DecimalField(decimal_places=4, default=0.495, max_digits=10),
        ),
    ]
