# Generated by Django 3.0.8 on 2020-08-15 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20200815_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentages',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_percentages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
